name: Publish graph

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: logseq/publish-spa@v0.3.1
        with:
          graph-directory: .
          output-directory: www
          theme-mode: dark

      - name: Add Mastodon verification link
        run: |
          sed -i 's#</head>#<link href="https://hachyderm.io/@xophmeister" rel="me" />\n</head>#' www/index.html

      - run: touch www/.nojekyll

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: www

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
